title: Hey Guys, I’m Lei Wang
description: I’m Lei Wang, a technical poet of China. This is my personal homepage.
keywords: [前端, JavaScript, TypeScript, Node.js, 工程化, Webpack, React, Vue.js, Flutter, 教程, 汪磊, zce, zce.me]
heading: Hey! Guys
slogan: I’m Lei Wang, a technical poet of China.
links:
  - text: Weibo
    href: https://weibo.com/zceme
    target: _blank
  - text: WeChat
    href: https://s.zce.me/qrcode/wechat.jpg
    target: _blank
  - text: Blog
    href: https://blog.zce.me
    target: _blank
  - text: GitHub
    href: https://github.com/zce
    target: _blank
  - text: Email
    href: mailto:w@zce.me
    target: _self
  - text: Donate
    href: https://s.zce.me/qrcode/reward.jpg
    target: _blank
  # - text: Discuss
  #   href: https://github.com/zce/discuss/issues
  #   target: _blank
analytics_id: 655e3d724e78de13d1a583921c7fdc19
